numpy
by aakarsh vyas

In [1]:
print("hello world")

hello world


In [2]:
a = 12

In [3]:
def hello ():
    print("who are you")

In [4]:
hello()

who are you


Basic array creation

In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [8]:
np.array(a)

array([1, 2, 3, 4])

In [9]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [11]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr = np.ones((6,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,5,6)
arr

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

Random Generation function

In [16]:
np.random.rand(10)

array([0.63409275, 0.95318522, 0.19173562, 0.95661574, 0.66172427,
       0.59664036, 0.22655093, 0.67583566, 0.90552405, 0.70679845])

In [17]:
np.random.randn(10)

array([-0.24789649, -0.81293016,  1.16239066, -0.05719842, -0.16799475,
        0.22616587,  0.12967482, -1.65661687,  0.04790389,  0.25693598])

In [18]:
np.random.randint(5)

2

In [19]:
np.random.randint(10,20,10)

array([14, 13, 14, 12, 14, 14, 12, 16, 15, 18], dtype=int32)

Array Attributes

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
 arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

Array Methods

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(9)

In [27]:
arr.sum()

np.int64(45)

In [28]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [29]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [30]:
arr.mean()

np.float64(5.0)

In [31]:
arr.std()

np.float64(2.581988897471611)

In [32]:
arr.argmax()

np.int64(8)

In [33]:
arr.argmin()

np.int64(0)

Reshaping and resizing


In [34]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

ARRAY INDEXING 

Numpy Indexing and Slicing of Vectors

In [36]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
arr[6]

np.int64(17)

In [38]:
arr[1:5]

array([12, 13, 14, 15])

In [39]:
arr[3::2]

array([14, 16, 18, 20])

In [40]:
arr[4]

np.int64(15)

Numpy Indexing And Slicing Of Matrix

In [41]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr[0]

array([1, 2, 3, 4, 5])

In [43]:
arr[5]

array([26, 27, 28, 29, 30])

In [44]:
arr[0,4]

np.int64(5)

In [45]:
arr[4,4]

np.int64(25)

In [46]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [47]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [48]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [49]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [51]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

ARRAY OPRATIONS

Arithmetic Operations

In [52]:
import numpy as np

In [53]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [54]:
a1 +a2

array([ 7,  9, 11, 13, 15])

In [55]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [56]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [57]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [58]:
a1 // a2

array([0, 0, 0, 0, 0])

In [59]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [60]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [61]:
arr + 10

array([20, 30, 40, 50])

In [62]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [64]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep And Shallow Copy

In [65]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [67]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [68]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
a[4:6] * 10

array([50, 60])

In [70]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
a
b = a

In [72]:
b[0] = 99

In [73]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [75]:
a
b = a.copy()

In [76]:
b[0] = 99

In [77]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Oprations

In [79]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [80]:
A

array([[1, 2],
       [3, 4]])

In [81]:
B

array([[5, 6],
       [7, 8]])

In [82]:
A * B

array([[ 5, 12],
       [21, 32]])

In [83]:
A @ B

array([[19, 22],
       [43, 50]])

In [84]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [85]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking Array

In [86]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [87]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [90]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [93]:
a = np.vsplit(c,2)

In [94]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [95]:
import numpy as np

In [96]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [97]:
b = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for rows is valid")

for rows is valid


In [98]:
c = np.sum(s,axis = 1)
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for columns is valid")

for columns is valid


In [99]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [100]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [101]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [102]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [103]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [104]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [105]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [106]:
#Increase Math marks of all students by 5.
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [107]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [108]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [109]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [110]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [112]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18,  0,  0],
       [20, 95, 85]])